#!/bin/bash
To="johnsonkumar445@gmail.com"
ram_free=$(free -mt |grep Total: | awk '{print $4}')
if [ $ram_free -le 3500 ]
then
echo "sending mail because ram free size is less than 3500"
echo "subject:warning, RAM free size is low"| sendmail $To
fi
